const styles = {
  root: {
    // position: 'relative',
    width: '1920px',
    height: '978px',
    padding: '36px',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: '36px',
    flexShrink: 0,
    display: 'flex',
  },

  line1: {
    // position: 'relative',
    display: 'flex',
    alignItems: 'flex-start',
    gap: '36px',
    // top: '20px',
  },

  table1: {
    // position: 'relative',
    display: 'flex',
    width: '435px',
    height: '435px',
    padding: '20px',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: '20px',
    backgroundColor: '#FFAAAF',
    boxShadow: '0px 4px 4px 0px rgba(0, 0, 0, 0.25)',
  },
  tle: {
    // position: 'relative',
    // width: '395px',
    // height: '30px',
    display: 'flex',
    alignItems: 'center',
    flex: 100,
    alignSelf: 'stretch',
  },
  bt1: {
    // position: 'relative',
    display: 'flex',
    width: '200px',
    // height: '30px',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'stretch',
  },
  bt1text: {
    display: 'flex',
    width: '200px',
    height: '30px',
    flexDirection: 'column',
    justifyContent: 'center',
    flexShrink: 0,
    color: '#000',
    fontFamily: 'Roboto',
    fontSize: '24px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 'normal',
    textAlign: 'left',
  },

  bt2: {
    // position: 'relative',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'stretch',
  },
  bt2text: {
    display: 'flex',
    width: '197px',
    // height: '30px',
    flexDirection: 'column',
    justifyContent: 'center',
    alignSelf: 'stretch',
    color: '#F00',
    textAlign: 'right',
    fontFamily: 'Roboto',
    fontSize: '20px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 'normal',
  },

  info: {
    // position: 'relative',
    display: 'flex',
    // width: '395px',
    height: '345px',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: '20px',
    // flexShrink: 0,
    alignSelf: 'stretch',
  },
  list0: {
    // position: 'relative',
    display: 'flex',
    height: '280px',
    flexDirection: 'column',
    alignItems: 'flex-start',
    flexShrink: 0,
    alignSelf: 'stretch',
  },

  dataf: {
    // position: 'relative',
    display: 'flex',
    // width: '395px',
    height: '30px',
    padding: '15px',
    alignItems: 'flex-start',
    flexShrink: 0,
    alignSelf: 'stretch',
  },

  datat: {
    // position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    flex: 100,
    alignSelf: 'stretch',
    color: '#000',
    fontFamily: 'Roboto',
    fontSize: '16px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 'normal',
    textAlign: 'left',
  },

  datat2: {
    // position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    flex: 100,
    alignSelf: 'stretch',
    color: '#F00',
    fontFamily: 'Roboto',
    fontSize: '16px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 'normal',
    textAlign: 'right',
  },

  pay: {
    // position: 'relative',
    display: 'flex',
    height: '45px',
    alignItems: 'flex-start',
    gap: '10px',
    flexShrink: 0,
    alignSelf: 'stretch',
    borderTop: '2px solid var(--Solid-000000, #000)',
  },

  payt1: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    flex: 100,
    alignSelf: 'stretch',
    color: '#000',
    textAlign: 'right',
    fontFamily: 'Roboto',
    fontSize: '20px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 'normal',
  },
  payt2: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    flex: 100,
    alignSelf: 'stretch',
    color: '#F00',
    textAlign: 'left',
    fontFamily: 'Roboto',
    fontSize: '20px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 'normal',
  },
};

export default styles;
