// AppBar Styles

const styles = {
  root: {
    position: 'fixed',
    left: '0',
    top: '0',
    width: '1920px',
    height: '102px',
    padding: '0 36px',
    margin: '0',
    backgroundColor: '#FFFFFF',
    borderBottom: '2px solid #DDDDDD',
    display: 'inline-flex',
    justifyContent: 'space-between',
  },
  leftSection: {
    position: 'relative',
    left: '0',
    top: '0',
    width: '645px',
    height: '102px',
    margin: '0',
    display: 'inline-flex',
    justifyContent: 'space-between',
  },
  logoButton: {
    position: 'relative',
    left: '0',
    top: '0',
    width: '200px',
    height: '100px',
    backgroundColor: '#FFFFFF',
  },
  rightSection: {
    position: 'relative',
    right: '0',
    top: '0',
    width: '430px',
    height: '102px',
    margin: '0',
    display: 'inline-flex',
    flexDirection: 'row-reverse',
  },
  currentDate: {
    position: 'relative',
    right: '0',
    top: '0',
    width: '200px',
    height: '100px',
    margin: '0',
    backgroundColor: '#FFFFFF',
    display: 'inline-flex',
    justifyContent: 'center',
    alignItems: 'center',
    fontSize: '18px',
  },
};

export default styles;
