const styles = {
  testmodal: {
    display: 'flex',
    width: '660px',
    height: '564px',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: '60px',
    borderRadius: '5px',
    position: 'fixed',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
  },
  testcon: {
    display: 'flex',
    width: '660px',
    height: '564px',
    padding: '36px',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: '60px',
    backgroundColor: '#FFF',
    boxShadow: '0px 4px 4px 0px rgba(0, 0, 0, 0.25)',
    // borderRadius: '5px',
    position: 'fixed',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
  },
  modaltitle: {
    display: 'flex',
    width: '588px',
    height: '60px',
    padding: '0',
    alignItems: 'flex-start',
    gap: '36px',
    alignSelf: 'stretch',
    margin: '0',
  },
  settitle: {
    display: 'flex',
    width: '492px',
    height: '60px',
    alignItems: 'center',
    gap: '10px',
    margin: 0,
  },
  settletext: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    flex: 100,
    alignSelf: 'stretch',
    color: '#000',
    fontFamily: 'Roboto',
    fontSize: '36px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 'normal',
    textAlign: 'left',
  },
  backb: {
    display: 'flex',
    width: '60px',
    height: '60px',
    padding: '18px',
    justifyContent: 'center',
    alignItems: 'center',
    gap: '10px',
    borderRadius: '5px',
    border: '2px solid var(--Solid-000000, #000)',
    background: '#FFF',
  },
  btngr: {
    display: 'flex',
    width: '588px',
    height: '372px',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: '36px',
    alignSelf: 'stretch',
    margin: '0',
    padding: '',
  },
  mdbtn: {
    display: 'flex',
    width: '588px',
    height: '100px',
    justifyContent: 'center',
    alignItems: 'center',
    gap: '10px',
    flexShrink: 0,
    alignSelf: 'stretch',
    borderRadius: '5px',
    border: '2px solid #000000',
    background: '#FFF',
    color: '#000',
    textAlign: 'center',
    fontFamily: 'Roboto',
    fontSize: '32px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 'normal',
  },
  testmodal2: {
    display: 'flex',
    width: '660px',
    height: '450px',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: '60px',
    borderRadius: '5px',
    position: 'fixed',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
  },
  testcon2: {
    display: 'flex',
    width: '660px',
    height: '450px',
    padding: '36px',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: '60px',
    backgroundColor: '#FFF',
    boxShadow: '0px 4px 4px 0px rgba(0, 0, 0, 0.25)',
    // borderRadius: '5px',
    position: 'fixed',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
  },
  mttitle: {
    display: 'flex',
    width: '588px',
    height: '60px',
    alignItems: 'flex-start',
    gap: '36px',
    flexShrink: 0,
    alignSelf: 'stretch',
    margin: 0,
  },
  mtst: {
    display: 'flex',
    width: '492px',
    height: '60px',
    alignItems: 'center',
    gap: '10px',
  },
  mtsttext: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    flex: 100,
    alignSelf: 'stretch',
    color: '#000',
    fontFamily: 'Roboto',
    fontSize: '36px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 'normal',
    textAlign: 'left',
  },
  inputform: {
    display: 'flex',
    width: '588px',
    height: '108px',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: '18px',
    flexShrink: 0,
    alignSelf: 'stretch',
    margin: 0,
  },
  ipt: {
    display: 'flex',
    width: '588px',
    height: '30px',
    alignItems: 'flex-start',
    gap: '10px',
    flexShrink: 0,
    margin: 0,
  },
  ipttext: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    flex: 100,
    alignSelf: 'stretch',
    color: '#000',
    fontFamily: 'Roboto',
    fontSize: '24px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 'normal',
    textAlign: 'left',
    margin: 0,
  },
  outline: {
    display: 'flex',
    width: '588px',
    height: '60px',
    // padding: '8px 12px',
    alignItems: 'center',
    gap: '10px',
    flexShrink: 0,
    // alignSelf: 'stretch',
    // borderRadius: '4px',
    // border: '1px solid var(--solid-00000042, rgba(0, 0, 0, 0.42))',
  },
  tablein: {
    display: 'flex',
    width: '564px',
    height: '44px',
    alignItems: 'center',
    gap: '10px',
    flex: 100,
    alignSelf: 'stretch',
  },
  titext: {
    color: '#000',
    fontFamily: 'Roboto',
    fontSize: '24px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '24px',
    letterSpacing: '0.5px',
  },
  tmform: {
    display: 'flex',
    width: '588px',
    height: '90px',
    alignItems: 'flex-start',
    gap: '36px',
    flexShrink: 0,
    alignSelf: 'stretch',
    padding: '0',
    margin: '0',
  },
  formbtn1: {
    display: 'flex',
    width: '368px',
    height: '90px',
    justifyContent: 'center',
    alignItems: 'center',
    gap: '10px',
    borderRadius: '5px',
    background: 'linear-gradient(90deg, #00D1FF 0%, #0066FF 100%)',
  },
  fb1name: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    flex: 100,
    alignSelf: 'stretch',
    color: '#FF0',
    textAlign: 'center',
    fontFamily: 'Roboto',
    fontSize: '28px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 'normal',
  },
  initbtn: {
    display: 'flex',
    width: '184px',
    height: '90px',
    padding: '20px',
    justifyContent: 'center',
    alignItems: 'center',
    gap: '10px',
    borderRadius: '5px',
    border: '2px solid var(--Solid-000000, #000)',
    background: '#FFF',
  },
  order: {
    display: 'inline-flex',
    position: 'relative',
    width: '1920px',
    height: '1080px',
    flexDirection: 'column',
    alignItems: 'flex-start',
    // background: '#EBEBEB',
    left: '0',
    top: '102px',
    // overflow: 'hidden',
  },
  movemodal: {
    display: 'flex',
    width: '660px',
    height: '498px',
    // padding: '36px',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: '60px',
    // borderRadius: '5px',
    background: '#FFF',
    boxShadow: '0px 4px 4px 0px rgba(0, 0, 0, 0.25)',
    position: 'fixed',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
  },
  modalmove: {
    display: 'flex',
    width: '660px',
    height: '498px',
    padding: '36px',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: '60px',
    backgroundColor: '#FFF',
    // boxShadow: '0px 4px 4px 0px rgba(0, 0, 0, 0.25)',
    // borderRadius: '5px',
    position: 'fixed',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
  },
  mvinputform: {
    display: 'flex',
    // width: '588px',
    height: '156px',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: '36px',
    flexShrink: 0,
    alignSelf: 'stretch',
    // margin: 0,
  },
  mviftext: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    flex: 100,
    alignSelf: 'stretch',
  },
  movesave: {
    display: 'flex',
    height: '90px',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: '10px',
    flexShrink: 0,
    alignSelf: 'stretch',
    borderRadius: '5px',
    background: 'linear-gradient(90deg, #00D1FF 0%, #06F 100%)',
  },
  savetext: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    flex: 100,
    alignSelf: 'stretch',
    color: '#FF0',
    textAlign: 'center',
    fontFamily: 'Roboto',
    fontSize: '28px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 'normal',
  },
  waringmodal: {
    display: 'flex',
    width: '660px',
    height: '372px',
    // padding: '36px',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: '60px',
    borderRadius: '5px',
    background: '#FFF',
    boxShadow: '0px 4px 4px 0px rgba(0, 0, 0, 0.25)',
    position: 'fixed',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
  },
  modalwaring: {
    display: 'flex',
    width: '660px',
    height: '372px',
    padding: '36px',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: '60px',
    // borderRadius: '5px',
    background: '#FFF',
    position: 'fixed',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
  },
  waringtext: {
    display: 'flex',
    height: '30px',
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'center',
    flex: 100,
    gap: '10px',
    flexShrink: 0,
    alignSelf: 'stretch',
    color: '#000',
    fontFamily: 'Roboto',
    fontSize: '24px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 'normal',
  },
  textcan: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    flex: 100,
    alignSelf: 'stretch',
    color: '#000',
    fontFamily: 'Roboto',
    fontSize: '28px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 'normal',
  },
};

export default styles;
